### ISSUE TITLE
Publish spec PDF as part of CI (rather than committing it directly to the repo)

### ISSUE THREAD

**Issue by jackkoenig** [chipsalliance/firrtl#1092]
As discussed here https://github.com/freechipsproject/firrtl/pull/1085#issuecomment-494150560.

**Type of issue**: other enhancement

**What is the use case for changing the behavior?**

**Impact**: no functional change

**Development Phase**: request

**Comment by seldridge** [comment]
Done in https://github.com/chipsalliance/firrtl-spec/pull/3.

The latest release of the PDF spec can now be accessed here: https://github.com/chipsalliance/firrtl-spec/releases/latest/download/spec.pdf
