### ISSUE TITLE
Add Protobuf FIRRTL Emitters

### ISSUE THREAD

**Issue by seldridge** [chipsalliance/firrtl#1696]
Add a new API that enables users to include FIRRTL emitters that write protobuf.

### Checklist

- [x] Did you write out a description of the feature you want to see?
- [x] Did you look around for any related features?
- [x] Did you specify relevant external information?

### Feature Description

Add the ability for users to include protobuf emitters like how they include FIRRTL emitters.

As one API idea, a user could do the following to write low FIRRTL to a `Foo.pb` file.

```bash
firrtl -i Foo.fir -X low -o Foo.pb
```

### Type of Feature

  - new feature/API                    

### Related Features

A user can manually do this with `firrtl.proto.ToProto.writeToStream`. However, no protobuf emitter transform exists making protobuf emission a second-class citizen.

### External Information

This was requested on Gitter/Matrix ([permalink](https://view.matrix.org/room/!FQBlZBRjRMgQBRocZx:matrix.org/?anchor=$issOVoHTC0pkcj61bwCOsUW1OUpEadOqeSsdQhoUSRo&offset=-10&highlight=$issOVoHTC0pkcj61bwCOsUW1OUpEadOqeSsdQhoUSRo)).

**Comment by jackkoenig** [comment]
One issue with deriving it from the file extension of the output file is it doesn't work with `-e`, so I think it needs to be a separate argument like `--emit-proto|-pb` or something.

**Comment by seldridge** [comment]
Yeah, good point.

The unambiguous option here is via `--custom-transforms` and with an output file annotation that's sensitive to a specific emitter. Since we now support multiple emitters, a single output file really isn't expressive enough for supporting multiple emitters.

I do think a simpler API could be supported like: `-Xlow:proto:modules:Foo.bar` or `-Xhigh:firrtl:circuit:Baz.qux`. These are equivalent to a more verbose option format, e.g., `--custom-transforms LowFirrtlEmitter --emitter-option LowFirrtlEmitter:proto --emitter-option LowFirrtlEmitter:modules --emitter-option LowFirrtlEmitter:filenameBase:Foo.bar`. But, there's a clear expansion of simpler, shorthand options to more complex ones.
