### ISSUE TITLE
Expression is used as a FEMALE but can only used as a MALE. so How to use Irrevocable().flip as input

### ISSUE THREAD

**Issue by JohnsonZ-microe** [chipsalliance/firrtl#1738]
I m working on a project which is to add an AXI4 crossbar on a system. The ports are written by using the term Irrevocable(..).flip

![sendpix3](https://user-images.githubusercontent.com/52376592/86553930-bca5fa00-bf7e-11ea-9eea-2a490d0d8cd5.jpg)

I want to attach the port to the pins of the top, so I write my codes like this

**definition of PIN class:**

```
class PinCtrl extends Bundle {
  val oval = Bool()
  val oe   = Bool()
  val ie   = Bool()
}

// Package up the inputs and outputs
// for the Pin
abstract class Pin extends Bundle {
  val i = new Bundle {
    val ival = Bool(INPUT)
  }
  val o: PinCtrl

  // Must be defined by the subclasses
  def default(): Unit
  def inputPin(pue: Bool = Bool(false)): Bool
  def outputPin(signal: Bool,
    pue: Bool = Bool(false),
    ds: Bool = Bool(false),
    ie: Bool = Bool(false)
  ): Unit
}
```

**pins definition:**
```
class AXI4_Pins[T <: Pin]( pingen: () => T, c:AXI4BundleParameters) extends AXI4_Pins_BASE(pingen, c) {

  val w_data = Vec(c.dataBits, pingen()) 
  val w_strb = Vec(c.dataBits/8, pingen())
  val w_last = pingen()
  val w_ready  = pingen()
  val w_valid  = pingen()

  val b_id = Vec(c.idBits, pingen())
  val b_resp = Vec(c.respBits, pingen())
  val b_ready  = pingen()
  val b_valid  = pingen()
}
```

connect pins to the ports
   ```
   ...
    pins.w_data.zipWithIndex.map { case (p, i) =>
      p.outputPin(port.w.bits.data(i), pue=true.B, ie = true.B)
    }
    pins.w_strb.zipWithIndex.map { case (p, i) =>
      p.outputPin(port.w.bits.strb(i), pue=true.B, ie = true.B)
    }
    pins.w_last.outputPin(port.w.bits.last, pue=true.B, ie = true.B)
    pins.w_valid.outputPin(port.w.valid, pue=true.B, ie = true.B)
    port.w.ready := pins.w_ready.inputPin(pue = true.B)
    


    pins.b_id.zipWithIndex.map { case (p,i) =>
      port.b.bits.id(i) := p.inputPin(pue = true.B)
    }
    pins.b_resp.zipWithIndex.map { case (p,i) =>
      port.b.bits.resp(i) := p.inputPin(pue = true.B)
    }
    port.b.valid := pins.b_valid.inputPin(pue = true.B)
    pins.b_ready.outputPin(port.b.ready, pue=true.B, ie = true.B)
```

I was expecting that it will successfully connected, then I got the error which totally confused me.
![sendpix0](https://user-images.githubusercontent.com/52376592/86552760-7f8c3880-bf7b-11ea-88fe-791866dba54b.jpg)
Here I put ports aw and b as contrast, when the ports are used as output like **aw**, it goes well, but when they are used as input like **b**, the errors occur, Seems that the Irrevocable(..).flip is a read-only object, but how to fix it.

The problem is mainly about how to call the Irrevocable. And what does .flip mean?
![sendpix4](https://user-images.githubusercontent.com/52376592/86554078-2faf7080-bf7f-11ea-82c0-0740dc215011.jpg)

### environment
- Chisel Verion: <3.0.1>

**Comment by jackkoenig** [comment]
Somehow missed this issue when originally filed. Traditionally in Chisel, the default direction is `Output`, so when something is "flipped" it becomes an `Input` (thus read-only). Now `IrrevocableIO` are bidirectional, so better terms than "Input" and "Output" are "Producer" and "Consumer". Flipping `IrrevocableIO` makes it a `Producer`, the `valid` and `bits` are Inputs while the `ready` is an Output.
