### ISSUE TITLE
Misleading wording indicates that {S,U}Int<0> are illegal when they are, apparently, not

### ISSUE THREAD

**Issue by neithernut** [chipsalliance/firrtl#2206]
Section 4.1.1 of the spec talks about "positive" integers. When talking about natural numbers, one doesn't consider 0 positive, and so do many people when talking about integers. Instead, the term "non-negative" should be used.

https://github.com/chipsalliance/firrtl/blob/39b89435319bae1cf9b13fa6a3528f48d96223b7/spec/spec.tex#L173

**Comment by albert-magyar** [comment]
Thanks for bringing this to our attention!
