### ISSUE TITLE
Annotation deserialization should not rely on "class" coming first

### ISSUE THREAD

**Issue by fabianschuiki** [chipsalliance/firrtl#2497]
The annotation deserialization in `JsonProtocol` assumes that the "class" field always appears first in a JSON object:
https://github.com/chipsalliance/firrtl/blob/8d2262c0566c5cc7fc66dec7d3e6d1f8102879b5/src/main/scala/firrtl/annotations/JsonProtocol.scala#L312-L325

This assumption breaks easily when the JSON file has been modified/processed/generated by an external tool. Looking for "class" in all fields of the `JObject` instead of pattern matching for the first field would make annotation deserialization a lot more robust.

**Comment by seldridge** [comment]
I agree that this is a bug. JSON dictionary order is unordered, so relying on this being the first entry is error prone (though apparently is how Json4s handles type hints so we've never hit this before).

For more info: in MLIR, dictionaries are stored in sorted order and this sorted order can (legally) leak to serialized JSON.

**Comment by jackkoenig** [comment]
It should be fairly easy to update line 318 to support `class` in any field. The question is, will json4s deserialization still work even if we collect the type hints correctly? If so, then this is a super easy fix, if not we have a bit of a problem.
