### ISSUE TITLE
How does a memory with multi-writer ports operate when they all write to a same address in the same clk step?

### ISSUE THREAD

**Issue by wky17** [chipsalliance/firrtl#2609]
I used chisel stage to transform the following chisel module to get a lofirrtl circuit:

```
class MemoryIO(val n: Int, val w: Int) extends Bundle {
  val clk = Input(Bool())
  val addr  = Input(UInt(log2Up(n).W))
  val datai = Input(UInt(w.W))
  val datao = Output(UInt(w.W))
  val en = Input(Bool())
  val we = Input(Bool())
}

class MultiClockMemory(ports: Int, n: Int = 1024, w: Int = 32) extends Module {
  val io = IO(new Bundle {
    val ps = Vec(ports, new MemoryIO(n, w))
  })

  val ram = SyncReadMem(n, UInt(w.W))

  for (i <- 0 until ports) {
    val p = io.ps(i)
    withClock(p.clk.asClock) {
      val datao = WireDefault(0.U(w.W))
      when(p.en) {
        datao := ram(p.addr)
        when(p.we) {
          ram(p.addr) := p.datai
        }
      }
      p.datao := datao
    }
  }
}
```
module MultiClockMemory tries to operate 3 readers and writers following the order of index in one clk step, and I got the following lofirrtl code by chisel stage:
```
mem ram : @[MultiClockMemory.scala 19:24]
      data-type => UInt<32>
      depth => 1024
      read-latency => 1
      write-latency => 1
      reader => datao_MPORT
      reader => datao_MPORT_1
      reader => datao_MPORT_2
      writer => MPORT
      writer => MPORT_1
      writer => MPORT_2
      read-under-write => undefined
```
I wonder how does Firrtl-interpreter handle these three readers and writers, and what would happens if three writers tried to write different data to the same address. And what would happens if it is also read at the same time?

**Comment by ekiwi** [comment]
> if three writers tried to write different data to the same address.

If there is more than one write to the same address the entry at that address essentially gets corrupted, i.e., it  could take on an arbitrary value.


> And what would happens if it is also read at the same time

Since your read-under-write behavior is set to `undefined`, that means that if you write and read to/from the same address in the same cycle, the result of the read will be an arbitrary value.

**Comment by wky17** [comment]
Does this the arbitrary value means not the old value or any of the new written value, but a random number or combination of different bits of old value and new values?

**Comment by ekiwi** [comment]
> Does this the arbitrary value means not the old value or any of the new written value, but a random number or combination of different bits of old value and new values?

Arbitrary means any random number. However, while the spec allows for that, implementations (i.e., different backends) might restrict the outcome to e.g., only the new or the old value. That isn't something you can rely on though.

If you want a specific read-under-write behavior, you can specify that you want to read either the new or the old value. Example: https://github.com/chipsalliance/chisel/blob/d574078b4a50c11621215c1bc1e54221326f1ba3/src/main/scala/chisel3/util/Decoupled.scala#L268 (using the `SyncReadMem.WriteFirst` option)
