### ISSUE TITLE
Reporting a vulnerability

### ISSUE THREAD

**Issue by igibek** [chipsalliance/firrtl#2631]
Hello! 

I hope you are doing well! 

We are a security research team. Our tool automatically detected a vulnerability in this repository. We want to disclose it responsibly.  GitHub has a feature called **Private vulnerability reporting**, which enables security research to privately disclose a vulnerability. Unfortunately, it is not enabled for this repository. 

Can you enable it, so that we can report it? 

Thanks in advance! 

PS: you can read about how to enable private vulnerability reporting here: https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository

**Comment by jackkoenig** [comment]
Thank you for reaching out and including us in your security research. I have enabled private vulnerability reporting on this repository, as well as on https://github.com/chipsalliance/chisel which has absorbed much of the code of this repository and will be the location of future feature development of this project.

That being said, we are happy to fix security vulnerabilities in this repository as well.
